In [1]:
import numpy as np

In [9]:
a = np.arange(5*5*5, dtype=np.float).reshape(1,5,5,5)
print(a.shape)
b= np.sum(a, 1)
print(b.shape)
c = np.expand_dims(b, 1)
print(c.shape)

(1, 5, 5, 5)
(1, 5, 5)
(1, 1, 5, 5)


In [16]:
a = np.zeros((2,2,2,2))
a[...,:,:] = 2
b= np.sum(a,1)
print(b)
print(b.shape)
c = np.expand_dims(b, 1)
print(c)

[[[4. 4.]
  [4. 4.]]

 [[4. 4.]
  [4. 4.]]]
(2, 2, 2)
[[[[4. 4.]
   [4. 4.]]]


 [[[4. 4.]
   [4. 4.]]]]
